### ISSUE TITLE
Alias diffs between puppetdb and certless

### ISSUE THREAD

**Issue by raphink** [camptocamp/puppet-catalog-diff#23]
When diffing between puppetdb and certless certificates (didn't try others), there are constant diffs on `alias` parameters for various types (`file`, `concat_file` and others).

**Comment by raphink** [comment]
Also the Stage type

**Comment by KlavsKlavsen** [comment]
@raphink Try the --ignore_parameters alias command shown in example in readme ?

**Comment by raphink** [comment]
Hey @KlavsKlavsen, thanks for the advice!

I actually added `--ignore_parameters` a few months ago precisely to circumvent this issue, so yeah, that's the idea 😁

I'm still keeping this issue open because I'd like to properly fix it in the future.
