### ISSUE TITLE
Parallelize pull and diff

### ISSUE THREAD

**Issue by raphink** [camptocamp/puppet-catalog-diff#24]
Pull and diff take a long time and use complementary resources (resp. network and CPU).

It would be useful to start diffing catalogs as soon as a pair it pulled.

**Comment by alexjfisher** [comment]
I'm also finding the tool using crazy amount of memory, since it loads all `to` and `from` catalogs into memory before diffing them.

PS. I'm not too keen on the 'stale bot' closing issues that are still relevant.

**Comment by raphink** [comment]
@alexjfisher Yes, I'm not a bit fan of stale bots either, but the amount of notifications and open issues I have is insane, so it's the least bad solution I have at the moment. I don't mind reopening if it's still relevant.

**Comment by raphink** [comment]
As a note, I don't really have time to implement that at the moment, but I'll gladly help if you want to do it @alexjfisher!

**Comment by raphink** [comment]
Let's keep this open still
