### ISSUE TITLE
doing diff on same node - 2 different environments?

### ISSUE THREAD

**Issue by KlavsKlavsen** [camptocamp/puppet-catalog-diff#41]
How would I go about using this for diff'ing catalog for the same node - for 2 different catalogs? 
I'd like to use this in CI - and generate catalog for "X" nodes - on both "master" and "merge-request-xxx" environment and see diffs..

**Comment by raphink** [comment]
See https://dev.to/camptocamp-ops/diffing-puppet-environments-1fno#ci-integration for the options I use for that need.
