### ISSUE TITLE
installation directions not working

### ISSUE THREAD

**Issue by aerickson** [camptocamp/puppet-catalog-diff#47]
Per https://forge.puppet.com/modules/camptocamp/catalog_diff, the tool can be installed with:

```bash
$ puppet module install camptocamp-catalog-diff
Notice: Preparing to install into /Users/aerickson/.puppetlabs/etc/code/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Error: Request to Puppet Forge failed.
  The server being queried was https://forgeapi.puppet.com/v3/releases?module=camptocamp-catalog-diff&sort_by=version&exclude_fields=readme,changelog,license,uri,module,tags,supported,file_size,downloads,created_at,updated_at,deleted_at
  The HTTP response we received was '400 Bad Request'
```

Visiting https://forgeapi.puppet.com/v3/releases?module=camptocamp-catalog-diff is says that `"'camptocamp-catalog-diff' is not a valid full modulename"`. 

It seems it just need to be an underscore... this works:

`puppet module install camptocamp-catalog_diff`

**Comment by raphink** [comment]
Hi there. This is not what the referenced documentation says. The command is:

```
puppet module install camptocamp-catalog_diff
```
